version: 2
updates:
  # Go dependencies
  - package-ecosystem: gomod
    directory: /app # where go.mod lives
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/app"
    schedule: { interval: "weekly" }
